- name: disable nodejs
  ansible.builtin.shell: dnf module disable nodejs -y

- name: enable nodejs
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed


- name: copy Catalogue Service
  ansible.builtin.copy:
   src: catalogue.service
   dest: /etc/systemd/system/catalogue.service

- name: Add the user 'roboshop'
  ansible.builtin.user:
    name: roboshop
    state: present

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /app
    state: directory


- name: Download the file and extract
  ansible.builtin.unarchive:
      src: "https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip"
      dest: /app
      remote_src: yes



- name: install npm
  ansible.builtin.dnf:
      name: npm
      state: installed

- name: mongodb-mongosh -y
  ansible.builtin.dnf:
      name: mongodb-mongosh
      state: installed

-

- name: load master data
  ansible.builtin.shell: mongosh --host 172.31.25.195 </app/db/master-data.js


- name: Start servive
  ansible.builtin.systemd_service:
    src: catalogue
    state: restarted
    enabled: yes
    demon_reload: yes

