- name: Add the user 'roboshop'
  ansible.builtin.user:
    name: roboshop

- name: Remove app content file
  ansible.builtin.file:
    path: /app
    state: absent


- name: create app content file
  ansible.builtin.file:
    path: /app
    state: directory

- name: download and Extract file content
  ansible.builtin.unarchive:
   src: https://roboshop-artifacts.s3.amazonaws.com/{{ component_name }}-v3.zip
   dest: /app
   remote_src: yes