- name: install maven
  ansible.builtin.dnf:
    name: maven
    state: installed

- name: artifact_download
  ansible.builtin.include_tasks:
    file: artifact_download.yml

- name: install maven dependencies
  ansible.builtin.shell: mvn clean package ; mv target/{{ component_name }}-1.0.jar {{ component_name }}.jar
  args:
    chdir: /app

- name: system_setup
  ansible.builtin.include_tasks:
    file: system_setup.yml


    #123